<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopRefundOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_refund_orders', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('member_id')->nullable();
            $table->integer('merch_id')->nullable();
            $table->integer('order_id')->nullable();
            $table->integer('order_goods_id')->nullable();
            $table->string('refundno', 191)->nullable();
            $table->decimal('price', 8, 2)->nullable();
            $table->decimal('apply_price', 8, 2)->nullable();
            $table->string('reason', 191)->nullable();
            $table->text('image')->nullable();
            $table->string('reply', 191)->nullable();
            $table->text('refund_address')->nullable();
            $table->string('expresscom', 191)->nullable();
            $table->string('expresssn', 191)->nullable();
            $table->string('rexpresscom', 191)->nullable();
            $table->string('rexpresssn', 191)->nullable();
            $table->tinyInteger('type')->nullable()->default(1);
            $table->tinyInteger('refund_type')->nullable()->default(1);
            $table->tinyInteger('status')->nullable()->default(0);
            $table->timestamp('send_time')->nullable();
            $table->timestamp('operate_time')->nullable();
            $table->timestamp('return_ime')->nullable();
            $table->timestamp('finish_time')->nullable();
            $table->nullableTimestamps();

            $table->index('user_id', 'shop_order_goods_refunds_user_id_index');
            $table->index('member_id', 'shop_order_goods_refunds_member_id_index');
            $table->index('merch_id', 'shop_order_goods_refunds_merch_id_index');
            $table->index('order_id', 'shop_order_goods_refunds_order_id_index');
            $table->index('order_goods_id', 'shop_order_goods_refunds_order_goods_id_index');
            $table->index('refundno', 'shop_order_goods_refunds_refundno_index');
            $table->index('type', 'shop_order_goods_refunds_type_index');
            $table->index('refund_type', 'shop_order_goods_refunds_refund_type_index');
            $table->index('created_at', 'shop_order_goods_refunds_created_at_index');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_refund_orders');
    }
}
