<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopOrderGoodsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_order_goods', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('agent_id')->nullable();
            $table->integer('order_id')->nullable();
            $table->integer('goods_id')->nullable();
            $table->decimal('price', 8, 2)->nullable();
            $table->decimal('old_price', 8, 2)->nullable();
            $table->integer('total')->nullable();
            $table->integer('refund_total')->nullable();
            $table->string('title', 191)->nullable();
            $table->string('thumb', 191)->nullable();
            $table->integer('option_id')->nullable();
            $table->string('option_name', 191)->nullable();
            $table->tinyInteger('nocommission')->nullable();
            $table->decimal('commissions', 8, 2)->nullable();
            $table->decimal('commission0', 8, 2)->nullable();
            $table->decimal('commission1', 8, 2)->nullable();
            $table->decimal('commission2', 8, 2)->nullable();
            $table->decimal('commission3', 8, 2)->nullable();
            $table->string('goodssn', 191)->nullable();
            $table->string('productsn', 191)->nullable();
            $table->string('expresscom', 191)->nullable();
            $table->string('expresssn', 191)->nullable();
            $table->tinyInteger('refund_status')->nullable();
            $table->integer('refundid')->nullable();
            $table->tinyInteger('iscomment')->nullable()->default(0);
            $table->timestamp('send_time')->nullable();
            $table->timestamp('refund_time')->nullable();
            $table->timestamp('fetch_time')->nullable();
            $table->nullableTimestamps();

            $table->index('user_id', 'shop_order_goods_user_id_index');
            $table->index('order_id', 'shop_order_goods_order_id_index');
            $table->index('goods_id', 'shop_order_goods_goods_id_index');
            $table->index('title', 'shop_order_goods_title_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_order_goods');
    }
}
