<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkZhuantiTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_zhuanti', function (Blueprint $table) {
            $table->increments('id');

            $table->string('title', 190)->nullable();  //专题的标题
            $table->string('thumb', 190)->nullable();  //专题banner长图
            $table->string('banner', 190)->nullable();  //专题banner（正方形图）

            $table->text('content')->nullable();  //专题的介绍文案题
            $table->timestamp('start_time')->nullable();  //专题活动开始时间戳
            $table->timestamp('end_time')->nullable();  //专题活动结束时间戳




            $table->nullableTimestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_zhuanti');
    }
}
