<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMemberLevelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('member_levels', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('level')->nullable(); //等级大小
            $table->string('name', 100)->nullable(); //等级名
            $table->string('logo', 191)->nullable();  //等级图标
            $table->decimal('group_rate1', 4, 2)->nullable(); //组长拿团队每笔订单的佣金比例
            $table->decimal('group_rate2', 4, 2)->nullable(); //团队某个人升级为组长后，老组长拿的新组长团队的佣金比例
            $table->decimal('commission_rate1', 4, 2)->nullable();  //自购佣金比例
            $table->decimal('commission_rate2', 4, 2)->nullable();  //拿下级的佣金比例
            $table->decimal('credit', 8, 2)->nullable();  //升级所需积分
            $table->decimal('price', 9, 2)->nullable(); //升级所需支付金额
            $table->integer('duration')->nullable(); // 等级有效时长 按天计算
            $table->string('description', 191)->nullable(); //等级描述
            $table->tinyInteger('default')->default(0)->comment('1不是默认 0默认'); //0默认1不是默认
            $table->tinyInteger('status')->default(1)->comment('0禁用，1正常'); //0禁用，1正常

            $table->nullableTimestamps();

            $table->index('user_id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('member_levels');
    }
}
