<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkJingxuantable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_jingxuan', function (Blueprint $table) {
            $table->increments('id');

            $table->string('title', 190)->nullable();  //宝贝标题
            $table->text('pic_url')->nullable();  //宝贝主图原始图像，可用于生成二维码图片

            $table->text('content')->nullable();  //单品导购内容（表情未处理）
            $table->decimal('price',12,2)->nullable();  //在售价
            $table->decimal('final_price',12,2)->nullable();  //宝贝券后价
            $table->decimal('coupon_price',12,2)->nullable();  //优惠券金额
            $table->decimal('commission_rate',12,2)->nullable();  //	佣金比例
            $table->integer('shares')->nullable();  //该商品被分享次数
            $table->text('show_content')->nullable();  //	导购文案展示内容，含表情
            $table->text('copy_content')->nullable();  //导购文案复制内容，含表情
            $table->text('show_comment')->nullable();  //朋友圈评论展示内容，含表情，多条评论用“|”做区分
            $table->text('copy_comment')->nullable();  //朋友圈评论复制内容，含表情，多条评论用“|”做区分

            $table->timestamp('show_at')->nullable();  //展示时间戳

            $table->nullableTimestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_jingxuan');
    }
}
