<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkEntranceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('tbk_entrances', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('category_id');//分类id
            $table->string ('logo', 191)->nullable (); //图标
            $table->string ('title', 191)->nullable (); //标题
            $table->string ('descrtption', 191)->nullable (); //描述
            $table->string ('url', 191)->nullable (); //跳转地址
            $table->softDeletes ();

            $table->index ('category_id', 'category_id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('tbk_entrances');
    }
}
