<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkHaohuoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_haohuo', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title', 190)->nullable();  //标题
            $table->string('content', 190)->nullable();  //专场导购内容
            $table->string('introduce', 190)->nullable();  //导购文案展示内容，含表情
            $table->string('app_hot_image', 190)->nullable();  //
            $table->string('text', 190)->nullable();  //导购文案复制内容，含表情
            $table->integer('shares')->nullable();  //分享次数
            $table->timestamp('start_time')->nullable();  //专场开始时间戳
            $table->timestamp('end_time')->nullable();  //专场结束时间戳
            $table->text('data')->nullable();  //9个商品数据 json

            $table->nullableTimestamps();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_haohuo');
    }
}
