<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMembersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('members', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('user_id')->nullable ();
            $table->integer ('inviter_id')->nullable ();
            $table->string ('wx_unionid', 191)->nullable ();
            $table->string ('wx_openid1', 191)->nullable ();
            $table->string ('wx_openid2', 191)->nullable ();
            $table->string ('ali_unionid', 191)->nullable ();
            $table->string ('ali_openid1', 191)->nullable ();
            $table->string ('ali_openid2', 191)->nullable ();
            $table->string ('nickname', 191)->nullable ();
            $table->string ('phone', 100)->nullable ();
            $table->string ('password', 191)->nullable ();
            $table->string ('headimgurl', 191)->nullable ();
            $table->tinyInteger ('isagent')->nullable ()->default (0);
            $table->decimal ('credit1', 8, 2)->nullable ()->default (0.00);
            $table->integer ('credit2')->nullable ()->default (0);
            $table->integer ('level1')->nullable ();
            $table->integer ('level2')->nullable ();
            $table->tinyInteger ('status')->nullable ()->default (1);
            $table->timestamp ('agent_time')->nullable ();
            $table->nullableTimestamps ();
            $table->softDeletes ();

            $table->unique ('wx_unionid');
            $table->unique ('wx_openid1');
            $table->unique ('wx_openid2');
            $table->unique ('ali_unionid');
            $table->unique ('ali_openid1');
            $table->unique ('ali_openid2');
            $table->unique ('phone');
            $table->index ('user_id');
            $table->index ('inviter_id');
            $table->index ('wx_unionid');
            $table->index ('wx_openid1');
            $table->index ('wx_openid2');
            $table->index ('ali_unionid');
            $table->index ('ali_openid1');
            $table->index ('ali_openid2');
            $table->index ('nickname');
            $table->index ('level1');
            $table->index ('level2');
            $table->index ('phone');
            $table->index ('status');
            $table->index ('created_at');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('members');
    }
}
