<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkOauthTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_oauth', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('sid')->nullable();
            $table->string('taoid')->nullable();
            $table->string('name', 100)->nullable();
            $table->string('token', 190)->nullable();
            $table->string('refresh_token', 190)->nullable();
            $table->timestamp('auth_time')->nullable();
            $table->timestamp('expire_time')->nullable();
            $table->tinyInteger('type')->nullable()->default(1);
            $table->nullableTimestamps();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_oauth');
    }
}
