<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopGoodsSpecItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_goods_spec_items', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('goods_id')->nullable();
            $table->string('title', 191)->nullable();
            $table->string('thumb', 191)->nullable();
            $table->integer('sort')->nullable();
            $table->tinyInteger('status')->nullable()->default(1);
            $table->nullableTimestamps();

            $table->index('user_id');
            $table->index('goods_id');
            $table->index('title');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_goods_spec_items');
    }
}
