<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkEntranceCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('tbk_entrance_categories', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('parent_id');//上级分类ID
            $table->string ('title', 191)->nullable (); //标题
            $table->integer ('sort')->nullable (); //排序
            $table->tinyInteger ('status')->nullable (); //是否显示
            $table->softDeletes ();

            $table->index ('pid', 'pid');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('tbk_entrance_categories');
    }
}
