<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMemberWithdrawsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('member_withdraws', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('member_id')->nullable();
            $table->decimal('money', 8, 2)->nullable()->default(0.00);
            $table->decimal('real_money', 8, 2)->nullable()->default(0.00);
            $table->decimal('deduct_money', 8, 2)->nullable()->default(0.00);
            $table->string('realname', 191)->nullable();
            $table->string('alipay', 191)->nullable();
            $table->string('bankname', 191)->nullable();
            $table->string('bankcard', 191)->nullable();
            $table->text('reason')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->tinyInteger('pay_type')->nullable();
            $table->timestamp('pay_time')->nullable();
            $table->timestamp('refused_time')->nullable();
            $table->nullableTimestamps();

            $table->index('user_id');
            $table->index('member_id');
            $table->index('status');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('member_withdraws');
    }
}
