<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMemberCreditLogsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('member_credit_logs', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('user_id')->nullable ();
            $table->integer ('member_id')->nullable ();
            $table->integer ('operater_id')->nullable ();
            $table->decimal ('credit', 8, 2)->nullable ()->default (0.00);
            $table->tinyInteger ('type')->nullable ();
            $table->string ('remark', 191)->nullable ();
            $table->nullableTimestamps ();

            $table->index ('member_id');
            $table->index ('type');
            $table->index ('user_id');
            $table->index ('operater_id');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('member_credit_logs');
    }
}
