<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserRechargesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_recharges', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->string('title', 191)->nullable();
            $table->string('out_trade_no', 191)->nullable();
            $table->decimal('money', 8, 2)->nullable()->default(0.00);
            $table->decimal('real_money', 8, 2)->nullable()->default(0.00);
            $table->decimal('giving_money', 8, 2)->nullable()->default(0.00);
            $table->tinyInteger('type')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->timestamp('pay_time')->nullable();
            $table->nullableTimestamps();

            $table->index('user_id', 'user_id_index');
            $table->index('status', 'status_index');
            $table->index('created_at', 'created_at_index');
            $table->index('out_trade_no', 'out_trade_no_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_recharges');
    }
}
