<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkUserFavouritesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_user_favourites', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->string('title', 190)->nullable(); //名称
            $table->string('pic_url', 190)->nullable(); //图片地址
            $table->string('item_id', 30)->nullable(); //优惠卷id
            $table->integer('volume')->nullable(); //销量
            $table->decimal('price', 9, 2)->nullable(); //原价
            $table->decimal('coupon_price', 9, 2)->nullable(); //优惠价
            $table->decimal('final_price', 9, 2)->nullable(); //最终价
            $table->string('type', 20)->nullable(); //1淘宝2京东3拼多多
            $table->nullableTimestamps();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_user_favourites');
    }
}
