<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkMemberFavouritesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_member_favourites', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('member_id')->nullable();
            $table->string('title', 190)->nullable();
            $table->string('pic_url', 190)->nullable();
            $table->string('item_id', 30)->nullable();
            $table->integer('volume')->nullable();
            $table->decimal('price', 9, 2)->nullable();
            $table->decimal('coupon_price', 9, 2)->nullable();
            $table->decimal('final_price', 9, 2)->nullable();
            $table->string('type', 20)->nullable();
            $table->nullableTimestamps();

            $table->index('member_id', 'member_id');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_member_favourites');
    }
}
