<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopGoodsTagsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shop_goods_tags', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->string('name', 191)->nullable();
            $table->integer('sort')->nullable()->default(100);
            $table->string('color', 191)->nullable();
            $table->tinyInteger('status')->nullable()->default(1);
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->index('user_id', 'shop_goods_tags_user_id_index');
            $table->index('name', 'shop_goods_tags_name_index');
            $table->index('status', 'shop_goods_tags_status_index');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('shop_goods_tags');
    }
}
