<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('shop_categories', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('user_id')->nullable ();
            $table->integer ('parentid')->nullable ()->default (0);
            $table->string ('name', 191)->nullable ();
            $table->string ('thumb', 191)->nullable ();
            $table->string ('description', 191)->nullable ();
            $table->string ('advimg', 191)->nullable ();
            $table->string ('advurl', 191)->nullable ();
            $table->integer ('sort')->nullable ()->default (100);
            $table->tinyInteger ('status')->nullable ()->default (1);
            $table->tinyInteger ('ishome')->nullable ()->default (0);
            $table->tinyInteger ('isrecommand')->nullable ()->default (0);
            $table->nullableTimestamps ();
            $table->softDeletes ();

            $table->index ('user_id');
            $table->index ('parentid');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('shop_categories');
    }
}
