<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');

            $table->integer('inviter_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->integer('oldgroup_id')->nullable();
            $table->string('wx_unionid', 191)->nullable();
            $table->string('wx_openid1', 191)->nullable();
            $table->string('wx_openid2', 191)->nullable();
            $table->string('ali_unionid', 191)->nullable();
            $table->string('ali_openid1', 191)->nullable();
            $table->string('ali_openid2', 191)->nullable();
            $table->string('nickname', 191)->nullable();
            $table->string('phone', 100)->nullable();
            $table->string('password', 191)->nullable();
            $table->string('headimgurl', 191)->nullable();
            $table->decimal('credit1', 8, 2)->nullable()->default(0.00); //金额
            $table->decimal('credit2', 8, 2)->nullable()->default(0.00); //积分
            $table->decimal('credit3', 8, 2)->nullable()->default(0.00); //经验值
            $table->integer('level_id')->nullable();
            $table->tinyInteger('is_default')->default(0)->comment('0 不是默认 1是默认');
            $table->string('realname', 191)->nullable();
            $table->string('alipay', 191)->nullable();
            $table->tinyInteger('status')->nullable()->default(1);
            $table->timestamp('expired_time')->nullable(); //等级到期时间
            $table->string('remember_token', 191)->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->unique('wx_unionid', 'users_wx_unionid_unique');
            $table->unique('wx_openid1', 'users_wx_openid1_unique');
            $table->unique('wx_openid2', 'users_wx_openid2_unique');
            $table->unique('ali_unionid', 'users_ali_unionid_unique');
            $table->unique('ali_openid1', 'users_ali_openid1_unique');
            $table->unique('ali_openid2', 'users_ali_openid2_unique');
            $table->unique('phone', 'users_phone_unique');
            $table->index('inviter_id', 'users_inviter_id_index');
            $table->index('group_id', 'users_group_id_index');
            $table->index('oldgroup_id', 'users_oldgroup_id_index');
            $table->index('wx_unionid', 'users_wx_unionid_index');
            $table->index('wx_openid1', 'users_wx_openid1_index');
            $table->index('wx_openid2', 'users_wx_openid2_index');
            $table->index('ali_unionid', 'users_ali_unionid_index');
            $table->index('ali_openid1', 'users_ali_openid1_index');
            $table->index('ali_openid2', 'users_ali_openid2_index');
            $table->index('nickname', 'users_nickname_index');
            $table->index('level_id', 'users_level_id_index');
            $table->index('phone', 'users_phone_index');
            $table->index('status', 'users_status_index');
            $table->index('created_at', 'users_created_at_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
