<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopOrderGoodsRefundsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('shop_order_goods_refunds', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('user_id')->nullable ();
            $table->integer ('member_id')->nullable ();
            $table->integer ('merch_id')->nullable ();
            $table->integer ('order_id')->nullable ();
            $table->integer ('order_goods_id')->nullable ();
            $table->string ('refundno', 191)->nullable ();
            $table->decimal ('price', 8, 2)->nullable ();
            $table->decimal ('apply_price', 8, 2)->nullable ();
            $table->string ('reason', 191)->nullable ();
            $table->text ('image')->nullable ();
            $table->string ('reply', 191)->nullable ();
            $table->text ('refund_address')->nullable ();
            $table->string ('expresscom', 191)->nullable ();
            $table->string ('expresssn', 191)->nullable ();
            $table->string ('rexpresscom', 191)->nullable ();
            $table->string ('rexpresssn', 191)->nullable ();
            $table->tinyInteger ('type')->nullable ()->default (1);
            $table->tinyInteger ('refund_type')->nullable ()->default (1);
            $table->tinyInteger ('status')->nullable ()->default (0);
            $table->timestamp ('send_time')->nullable ();
            $table->timestamp ('operate_time')->nullable ();
            $table->timestamp ('return_ime')->nullable ();
            $table->timestamp ('finish_time')->nullable ();
            $table->nullableTimestamps ();

            $table->index ('user_id');
            $table->index ('member_id');
            $table->index ('merch_id');
            $table->index ('order_id');
            $table->index ('order_goods_id');
            $table->index ('refundno');
            $table->index ('type');
            $table->index ('refund_type');
            $table->index ('created_at');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('shop_order_goods_refunds');
    }
}
