<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTbkOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbk_orders', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->unsignedInteger('member_id')->nullable();
            $table->integer('group_id')->nullable()->comment('组ID');
            $table->integer('oldgroup_id')->nullable()->comment('旧组ID');
            $table->string('ordernum', 20)->nullable()->comment('订单号');
            $table->string('title', 190)->nullable()->comment('订单名');
            $table->string('itemid', 20)->nullable()->comment('商品ID');
            $table->integer('count')->nullable()->comment('商品数');
            $table->decimal('price', 9, 2)->nullable()->comment('单价');
            $table->decimal('final_price', 9, 2)->nullable()->comment('付款价格');
            $table->string('commission_rate', 10)->nullable()->comment('分成比率');
            $table->decimal('commission_amount', 6, 2)->nullable()->comment('预估收入');
            $table->string('pid', 50)->nullable()->comment('推广位');
            $table->tinyInteger('status')->nullable()->comment('1已付款 2已结算 3已失效 '); //已付款(已付款、待返利) 已结算(已返利) 已失效(已退货、已失效)
            $table->tinyInteger('type')->nullable()->comment('1淘宝 2京东 3拼多多');
            $table->timestamp('complete_at')->nullable()->comment('完成时间');
            $table->nullableTimestamps();

            $table->index('member_id');
            $table->index('ordernum');
            $table->index('title');
            $table->index('user_id');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbk_orders');
    }
}
