<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateShopGoodsOptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('shop_goods_options', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('user_id')->nullable ();
            $table->integer ('goods_id')->nullable ();
            $table->string ('title', 191)->nullable ();
            $table->string ('thumb', 191)->nullable ();
            $table->decimal ('price', 8, 2)->nullable ();
            $table->decimal ('old_price', 8, 2)->nullable ();
            $table->decimal ('cost_price', 8, 2)->nullable ();
            $table->integer ('total')->nullable ();
            $table->decimal ('weight', 8, 2)->nullable ();
            $table->string ('specs', 191)->nullable ();
            $table->string ('goodssn', 191)->nullable ();
            $table->string ('productsn', 191)->nullable ();
            $table->integer ('sort')->nullable ()->default (0);
            $table->nullableTimestamps ();

            $table->index ('user_id');
            $table->index ('goods_id');
            $table->index ('title');
            $table->index ('goodssn');
            $table->index ('productsn');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('shop_goods_options');
    }
}
