<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMemberLevelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create ('member_levels', function (Blueprint $table) {
            $table->increments ('id');
            $table->integer ('user_id')->nullable ();
            $table->string ('name', 191)->nullable ()->default ('');
            $table->string ('logo', 191)->nullable ()->default ('');
            $table->integer ('level')->nullable ();
            $table->decimal ('discount', 8, 2)->nullable ()->default (0.00);
            $table->integer ('credit')->nullable ()->default (0);
            $table->decimal ('money', 8, 2)->nullable ();
            $table->integer ('sort')->nullable ()->default (100);
            $table->tinyInteger ('status')->nullable ();
            $table->nullableTimestamps ();

            $table->index ('user_id');
            $table->index ('name');
            $table->index ('status');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists ('member_levels');
    }
}
