<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDianOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('dian_orders', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('dian_id')->nullable();  //小店id
            $table->integer('user_id')->nullable();  //付款人id
            $table->string('transaction_id', 191)->nullable();  //微信付款单号
            $table->string('out_trade_no', 191)->nullable(); //本地订单号
            $table->string('title', 191)->nullable(); //订单标题
            $table->string('remark')->nullable(); //订单备注 用户付款时填写
            $table->decimal('money')->nullable()->default(0); //应付款金额
            $table->decimal('real_money')->nullable()->default(0); //实际付款金额pay
            $table->tinyInteger('status')->nullable()->comment('1 支付完成 2 支付未完成 3已退款');
            $table->string('pay_type')->nullable(); //付款类型 1微信 2支付宝 3线下
            $table->timestamp('payment_at')->nullable()->comment('支付完成时间');
            $table->nullableTimestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('dian_orders');
    }
}
