<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserHistoriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_histories', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->integer('merch_id')->nullable();
            $table->integer('goods_id')->nullable();
            $table->integer('views')->nullable();
            $table->nullableTimestamps();
            $table->softDeletes();

            $table->index('user_id', 'member_histories_user_id_index');
            $table->index('merch_id', 'member_histories_merch_id_index');
            $table->index('goods_id', 'member_histories_goods_id_index');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('member_histories');
    }
}
